### ISSUE TITLE
Sending cuota exceeded

### ISSUE THREAD

**Issue by juandamage** [karan173/Multi-Forward-for-Gmail#2]
Hi,

Sometimes, extension says that sending cuota is exceeded, Im using Google Apps for Work, and i never forward about 1500 mails per day..

What can be happen?
Thanks in advance for your help!

**Comment by karan173** [comment]
Do you forward these to multiple recipients. The way it is counted is - if you forward 4 mails to 3 people, it is counted as 12 mails forwarded. Also note that the time zone used by Google to refresh their quota, may not be the same as your time zone.

**Comment by juandamage** [comment]
Yes, that was the problem
Thank you very much for your attention and quick response.
A great job! Regards!
